amcl:
  ros__parameters:
    use_sim_time: false
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    do_beamskip: true
    global_frame_id: "map"
    lambda_short: 0.1
    laser_max_range: 12.0
    laser_min_range: 0.1
    max_beams: 60
    min_particles: 100
    max_particles: 3000
    odom_frame_id: "odom"
    recovery_alpha_slow: 0.0
    recovery_alpha_fast: 0.0
    resample_interval: 2
    scan_topic: "scan"
    set_initial_pose: true
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_d: 0.25
    update_min_a: 0.2

bt_navigator:
  ros__parameters:
    use_sim_time: false

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.25
      lookahead_dist: 0.6
      use_velocity_scaled_lookahead_dist: true
      min_lookahead_dist: 0.4

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: "odom"
      robot_base_frame: "base_footprint"
      update_frequency: 10.0
      publish_frequency: 10.0
      rolling_window: true
      width: 3.0
      height: 3.0
      resolution: 0.05
      robot_radius: 0.105
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: "scan"
        scan:
          topic: "scan"
          max_obstacle_height: 2.0
          clearing: true
          marking: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.15   # 🔵 Small inflation radius (normally 0.55)
        cost_scaling_factor: 5.0  # Red/Blue transition tuning

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: "map"
      robot_base_frame: "base_footprint"
      update_frequency: 1.0
      publish_frequency: 1.0
      rolling_window: false
      width: 10.0
      height: 10.0
      resolution: 0.05
      robot_radius: 0.105
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
        enabled: true
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: "scan"
        scan:
          topic: "scan"
          max_obstacle_height: 2.0
          clearing: true
          marking: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.15   # 🔵 Small inflation radius
        cost_scaling_factor: 5.0  # 🔴 Steeper cost dropoff (sharp blue-red edge)

planner_server:
  ros__parameters:
    use_sim_time: false
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false

recoveries_server:
  ros__parameters:
    use_sim_time: false
    recovery_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    backup:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"

waypoint_follower:
  ros__parameters:
    use_sim_time: false
    stop_on_failure: true
    loop_rate: 20

